// Code generated by gen.go from entities.json; DO NOT EDIT.

package entity

import "github.com/ungerik/go-mx"

// HTML named character references. Each renders the named entity shown,
// which the browser displays as the corresponding character.
const (
	// Markup characters that must be escaped to appear literally.

	LessThan    mx.Raw = `&lt;`   // < less-than sign
	GreaterThan mx.Raw = `&gt;`   // > greater-than sign
	Ampersand   mx.Raw = `&amp;`  // & ampersand
	DoubleQuote mx.Raw = `&quot;` // " quotation mark
	SingleQuote mx.Raw = `&apos;` // ' apostrophe

	// Spaces and invisible formatting.

	NonBreakingSpace   mx.Raw = `&nbsp;`           // non-breaking space (no line break)
	EnSpace            mx.Raw = `&ensp;`           // en space (width of an en)
	EmSpace            mx.Raw = `&emsp;`           // em space (width of an em)
	ThinSpace          mx.Raw = `&thinsp;`         // thin space
	HairSpace          mx.Raw = `&hairsp;`         // hair space (thinnest space)
	FigureSpace        mx.Raw = `&numsp;`          // figure space (width of a digit)
	PunctuationSpace   mx.Raw = `&puncsp;`         // punctuation space
	ZeroWidthSpace     mx.Raw = `&ZeroWidthSpace;` // zero-width space (allows a line break)
	ZeroWidthNonJoiner mx.Raw = `&zwnj;`           // zero-width non-joiner
	ZeroWidthJoiner    mx.Raw = `&zwj;`            // zero-width joiner
	LeftToRightMark    mx.Raw = `&lrm;`            // left-to-right mark (bidi control)
	RightToLeftMark    mx.Raw = `&rlm;`            // right-to-left mark (bidi control)
	SoftHyphen         mx.Raw = `&shy;`            // soft hyphen (visible only at a line break)

	// Currency signs.

	Cent     mx.Raw = `&cent;`   // ¢ cent sign
	Pound    mx.Raw = `&pound;`  // £ pound sign
	Yen      mx.Raw = `&yen;`    // ¥ yen sign
	Euro     mx.Raw = `&euro;`   // € euro sign
	Currency mx.Raw = `&curren;` // ¤ generic currency sign
	Florin   mx.Raw = `&fnof;`   // ƒ florin sign

	// Legal and editorial marks.

	Copyright               mx.Raw = `&copy;`   // © copyright sign
	Registered              mx.Raw = `&reg;`    // ® registered-trademark sign
	Trademark               mx.Raw = `&trade;`  // ™ trademark sign
	SoundRecordingCopyright mx.Raw = `&copysr;` // ℗ sound-recording copyright sign

	// Punctuation and typography.

	EmDash        mx.Raw = `&mdash;`  // — em dash
	EnDash        mx.Raw = `&ndash;`  // – en dash
	HorizontalBar mx.Raw = `&horbar;` // ― horizontal bar (quotation dash)
	Ellipsis      mx.Raw = `&hellip;` // … horizontal ellipsis
	Bullet        mx.Raw = `&bull;`   // • bullet
	MiddleDot     mx.Raw = `&middot;` // · middle dot
	SectionSign   mx.Raw = `&sect;`   // § section sign
	Paragraph     mx.Raw = `&para;`   // ¶ pilcrow (paragraph) sign
	Numero        mx.Raw = `&numero;` // № numero sign
	Dagger        mx.Raw = `&dagger;` // † dagger
	DoubleDagger  mx.Raw = `&Dagger;` // ‡ double dagger
	PerMille      mx.Raw = `&permil;` // ‰ per-mille sign
	Prime         mx.Raw = `&prime;`  // ′ prime (feet, minutes)
	DoublePrime   mx.Raw = `&Prime;`  // ″ double prime (inches, seconds)
	Overline      mx.Raw = `&oline;`  // ‾ overline (spacing overscore)

	// Quotation marks and guillemets.

	LeftDoubleQuote      mx.Raw = `&ldquo;`  // “ left double quotation mark
	RightDoubleQuote     mx.Raw = `&rdquo;`  // ” right double quotation mark
	LeftSingleQuote      mx.Raw = `&lsquo;`  // ‘ left single quotation mark
	RightSingleQuote     mx.Raw = `&rsquo;`  // ’ right single quotation mark (also apostrophe)
	DoubleLowQuote       mx.Raw = `&bdquo;`  // „ double low-9 quotation mark
	SingleLowQuote       mx.Raw = `&sbquo;`  // ‚ single low-9 quotation mark
	LeftGuillemet        mx.Raw = `&laquo;`  // « left-pointing double angle quotation mark
	RightGuillemet       mx.Raw = `&raquo;`  // » right-pointing double angle quotation mark
	LeftSingleGuillemet  mx.Raw = `&lsaquo;` // ‹ single left-pointing angle quotation mark
	RightSingleGuillemet mx.Raw = `&rsaquo;` // › single right-pointing angle quotation mark

	// Superscripts and vulgar fractions.

	Superscript1  mx.Raw = `&sup1;`   // ¹ superscript one
	Superscript2  mx.Raw = `&sup2;`   // ² superscript two
	Superscript3  mx.Raw = `&sup3;`   // ³ superscript three
	OneHalf       mx.Raw = `&frac12;` // ½ one half
	OneThird      mx.Raw = `&frac13;` // ⅓ one third
	TwoThirds     mx.Raw = `&frac23;` // ⅔ two thirds
	OneQuarter    mx.Raw = `&frac14;` // ¼ one quarter
	ThreeQuarters mx.Raw = `&frac34;` // ¾ three quarters
	OneFifth      mx.Raw = `&frac15;` // ⅕ one fifth
	TwoFifths     mx.Raw = `&frac25;` // ⅖ two fifths
	ThreeFifths   mx.Raw = `&frac35;` // ⅗ three fifths
	FourFifths    mx.Raw = `&frac45;` // ⅘ four fifths
	OneSixth      mx.Raw = `&frac16;` // ⅙ one sixth
	FiveSixths    mx.Raw = `&frac56;` // ⅚ five sixths
	OneEighth     mx.Raw = `&frac18;` // ⅛ one eighth
	ThreeEighths  mx.Raw = `&frac38;` // ⅜ three eighths
	FiveEighths   mx.Raw = `&frac58;` // ⅝ five eighths
	SevenEighths  mx.Raw = `&frac78;` // ⅞ seven eighths

	// Mathematical operators.

	PlusMinus           mx.Raw = `&plusmn;`    // ± plus-minus sign
	MinusPlus           mx.Raw = `&mnplus;`    // ∓ minus-or-plus sign
	Times               mx.Raw = `&times;`     // × multiplication sign
	Divide              mx.Raw = `&divide;`    // ÷ division sign
	Minus               mx.Raw = `&minus;`     // − minus sign (typographic, not a hyphen)
	Asterisk            mx.Raw = `&lowast;`    // ∗ asterisk operator
	DotOperator         mx.Raw = `&sdot;`      // ⋅ dot operator
	RingOperator        mx.Raw = `&compfn;`    // ∘ ring operator (function composition)
	SquareRoot          mx.Raw = `&radic;`     // √ square root (radical)
	Summation           mx.Raw = `&sum;`       // ∑ n-ary summation
	Product             mx.Raw = `&prod;`      // ∏ n-ary product
	Coproduct           mx.Raw = `&coprod;`    // ∐ n-ary coproduct
	Integral            mx.Raw = `&int;`       // ∫ integral
	DoubleIntegral      mx.Raw = `&Int;`       // ∬ double integral
	TripleIntegral      mx.Raw = `&tint;`      // ∭ triple integral
	ContourIntegral     mx.Raw = `&oint;`      // ∮ contour integral
	PartialDifferential mx.Raw = `&part;`      // ∂ partial differential
	Nabla               mx.Raw = `&nabla;`     // ∇ nabla (del / gradient)
	Infinity            mx.Raw = `&infin;`     // ∞ infinity
	Proportional        mx.Raw = `&prop;`      // ∝ proportional to
	Angle               mx.Raw = `&ang;`       // ∠ angle
	MeasuredAngle       mx.Raw = `&angmsd;`    // ∡ measured angle
	Perpendicular       mx.Raw = `&perp;`      // ⊥ perpendicular (up tack)
	Parallel            mx.Raw = `&parallel;`  // ∥ parallel to
	NotParallel         mx.Raw = `&nparallel;` // ∦ not parallel to
	Therefore           mx.Raw = `&there4;`    // ∴ therefore
	Because             mx.Raw = `&because;`   // ∵ because
	Degree              mx.Raw = `&deg;`       // ° degree sign
	Micro               mx.Raw = `&micro;`     // µ micro sign
	FractionSlash       mx.Raw = `&frasl;`     // ⁄ fraction slash

	// Set theory.

	EmptySet           mx.Raw = `&empty;`    // ∅ empty set
	ElementOf          mx.Raw = `&isin;`     // ∈ element of
	NotElementOf       mx.Raw = `&notin;`    // ∉ not an element of
	Contains           mx.Raw = `&ni;`       // ∋ contains as member
	NotContains        mx.Raw = `&notni;`    // ∌ does not contain as member
	Intersection       mx.Raw = `&cap;`      // ∩ intersection
	Union              mx.Raw = `&cup;`      // ∪ union
	Subset             mx.Raw = `&sub;`      // ⊂ subset of
	Superset           mx.Raw = `&sup;`      // ⊃ superset of
	NotSubset          mx.Raw = `&nsub;`     // ⊄ not a subset of
	SubsetEqual        mx.Raw = `&sube;`     // ⊆ subset of or equal to
	SupersetEqual      mx.Raw = `&supe;`     // ⊇ superset of or equal to
	NotSubsetEqual     mx.Raw = `&nsube;`    // ⊈ neither a subset of nor equal to
	NotSupersetEqual   mx.Raw = `&nsupe;`    // ⊉ neither a superset of nor equal to
	SetMinus           mx.Raw = `&setminus;` // ∖ set minus (difference)
	SubsetNotEqual     mx.Raw = `&subne;`    // ⊊ subset of, not equal to
	SupersetNotEqual   mx.Raw = `&supne;`    // ⊋ superset of, not equal to
	SquareSubset       mx.Raw = `&sqsub;`    // ⊏ square image of (square subset)
	SquareSuperset     mx.Raw = `&sqsup;`    // ⊐ square original of (square superset)
	SquareIntersection mx.Raw = `&sqcap;`    // ⊓ square cap (intersection)
	SquareUnion        mx.Raw = `&sqcup;`    // ⊔ square cup (union)
	BigUnion           mx.Raw = `&xcup;`     // ⋃ n-ary union
	BigIntersection    mx.Raw = `&xcap;`     // ⋂ n-ary intersection

	// Logic.

	ForAll       mx.Raw = `&forall;` // ∀ for all
	ThereExists  mx.Raw = `&exist;`  // ∃ there exists
	NotExists    mx.Raw = `&nexist;` // ∄ there does not exist
	LogicalAnd   mx.Raw = `&and;`    // ∧ logical and
	LogicalOr    mx.Raw = `&or;`     // ∨ logical or
	LogicalNot   mx.Raw = `&not;`    // ¬ not sign (negation)
	DirectSum    mx.Raw = `&oplus;`  // ⊕ circled plus (direct sum)
	CircledTimes mx.Raw = `&otimes;` // ⊗ circled times (tensor product)
	CircledDot   mx.Raw = `&odot;`   // ⊙ circled dot operator
	CircledMinus mx.Raw = `&ominus;` // ⊖ circled minus
	CircledSlash mx.Raw = `&osol;`   // ⊘ circled division slash

	// Relations.

	NotEqual            mx.Raw = `&ne;`     // ≠ not-equal sign
	LessOrEqual         mx.Raw = `&le;`     // ≤ less-than-or-equal sign
	GreaterOrEqual      mx.Raw = `&ge;`     // ≥ greater-than-or-equal sign
	NotLess             mx.Raw = `&nless;`  // ≮ not less-than
	NotGreater          mx.Raw = `&ngtr;`   // ≯ not greater-than
	NotLessOrEqual      mx.Raw = `&nle;`    // ≰ neither less-than nor equal to
	NotGreaterOrEqual   mx.Raw = `&nge;`    // ≱ neither greater-than nor equal to
	MuchLess            mx.Raw = `&ll;`     // ≪ much less-than
	MuchGreater         mx.Raw = `&gg;`     // ≫ much greater-than
	Approximately       mx.Raw = `&asymp;`  // ≈ approximately-equal sign
	TildeOperator       mx.Raw = `&sim;`    // ∼ tilde operator (similar to)
	AsymptoticallyEqual mx.Raw = `&simeq;`  // ≃ asymptotically equal to
	Congruent           mx.Raw = `&cong;`   // ≅ approximately equal to (congruent)
	Identical           mx.Raw = `&equiv;`  // ≡ identical to (equivalent)
	NotIdentical        mx.Raw = `&nequiv;` // ≢ not identical to
	NotTilde            mx.Raw = `&nsim;`   // ≁ not similar to
	VeryMuchLess        mx.Raw = `&Ll;`     // ⋘ much much less-than
	VeryMuchGreater     mx.Raw = `&Gg;`     // ⋙ much much greater-than
	LessTilde           mx.Raw = `&lsim;`   // ≲ less-than or similar to
	GreaterTilde        mx.Raw = `&gsim;`   // ≳ greater-than or similar to

	// Letterlike and blackboard symbols.

	Reals         mx.Raw = `&reals;`       // ℝ set of real numbers
	Complexes     mx.Raw = `&complexes;`   // ℂ set of complex numbers
	Integers      mx.Raw = `&integers;`    // ℤ set of integers
	Naturals      mx.Raw = `&naturals;`    // ℕ set of natural numbers
	Rationals     mx.Raw = `&rationals;`   // ℚ set of rational numbers
	Quaternions   mx.Raw = `&quaternions;` // ℍ set of quaternions
	RealPart      mx.Raw = `&real;`        // ℜ real part (black-letter R)
	ImaginaryPart mx.Raw = `&image;`       // ℑ imaginary part (black-letter I)
	Weierstrass   mx.Raw = `&weierp;`      // ℘ Weierstrass power set / p
	Aleph         mx.Raw = `&aleph;`       // ℵ aleph (transfinite cardinal)
	ReducedPlanck mx.Raw = `&planck;`      // ℏ reduced Planck constant (h-bar)
	ScriptL       mx.Raw = `&ell;`         // ℓ script small l (e.g. liters)

	// Greek small letters.

	Alpha         mx.Raw = `&alpha;`    // α Greek small letter alpha
	Beta          mx.Raw = `&beta;`     // β Greek small letter beta
	Gamma         mx.Raw = `&gamma;`    // γ Greek small letter gamma
	Delta         mx.Raw = `&delta;`    // δ Greek small letter delta
	Epsilon       mx.Raw = `&epsilon;`  // ε Greek small letter epsilon
	Zeta          mx.Raw = `&zeta;`     // ζ Greek small letter zeta
	Eta           mx.Raw = `&eta;`      // η Greek small letter eta
	Theta         mx.Raw = `&theta;`    // θ Greek small letter theta
	Iota          mx.Raw = `&iota;`     // ι Greek small letter iota
	Kappa         mx.Raw = `&kappa;`    // κ Greek small letter kappa
	Lambda        mx.Raw = `&lambda;`   // λ Greek small letter lambda
	Mu            mx.Raw = `&mu;`       // μ Greek small letter mu
	Nu            mx.Raw = `&nu;`       // ν Greek small letter nu
	Xi            mx.Raw = `&xi;`       // ξ Greek small letter xi
	Omicron       mx.Raw = `&omicron;`  // ο Greek small letter omicron
	Pi            mx.Raw = `&pi;`       // π Greek small letter pi
	Rho           mx.Raw = `&rho;`      // ρ Greek small letter rho
	Sigma         mx.Raw = `&sigma;`    // σ Greek small letter sigma
	FinalSigma    mx.Raw = `&sigmaf;`   // ς Greek small letter final sigma
	Tau           mx.Raw = `&tau;`      // τ Greek small letter tau
	Upsilon       mx.Raw = `&upsilon;`  // υ Greek small letter upsilon
	Phi           mx.Raw = `&phi;`      // φ Greek small letter phi
	Chi           mx.Raw = `&chi;`      // χ Greek small letter chi
	Psi           mx.Raw = `&psi;`      // ψ Greek small letter psi
	Omega         mx.Raw = `&omega;`    // ω Greek small letter omega
	ThetaSymbol   mx.Raw = `&thetasym;` // ϑ Greek theta symbol
	PhiSymbol     mx.Raw = `&phiv;`     // ϕ Greek phi symbol
	PiSymbol      mx.Raw = `&piv;`      // ϖ Greek pi symbol
	EpsilonSymbol mx.Raw = `&epsiv;`    // ϵ Greek lunate epsilon symbol
	VarRho        mx.Raw = `&rhov;`     // ϱ Greek rho symbol
	VarKappa      mx.Raw = `&varkappa;` // ϰ Greek kappa symbol

	// Greek capital letters (those distinct from Latin).

	CapGamma   mx.Raw = `&Gamma;`   // Γ Greek capital letter gamma
	CapDelta   mx.Raw = `&Delta;`   // Δ Greek capital letter delta
	CapTheta   mx.Raw = `&Theta;`   // Θ Greek capital letter theta
	CapLambda  mx.Raw = `&Lambda;`  // Λ Greek capital letter lambda
	CapXi      mx.Raw = `&Xi;`      // Ξ Greek capital letter xi
	CapPi      mx.Raw = `&Pi;`      // Π Greek capital letter pi
	CapSigma   mx.Raw = `&Sigma;`   // Σ Greek capital letter sigma
	CapUpsilon mx.Raw = `&Upsilon;` // Υ Greek capital letter upsilon
	CapPhi     mx.Raw = `&Phi;`     // Φ Greek capital letter phi
	CapPsi     mx.Raw = `&Psi;`     // Ψ Greek capital letter psi
	CapOmega   mx.Raw = `&Omega;`   // Ω Greek capital letter omega

	// Arrows.

	LeftArrow            mx.Raw = `&larr;`   // ← leftwards arrow
	RightArrow           mx.Raw = `&rarr;`   // → rightwards arrow
	UpArrow              mx.Raw = `&uarr;`   // ↑ upwards arrow
	DownArrow            mx.Raw = `&darr;`   // ↓ downwards arrow
	LeftRightArrow       mx.Raw = `&harr;`   // ↔ left-right arrow
	UpDownArrow          mx.Raw = `&varr;`   // ↕ up-down arrow
	UpLeftArrow          mx.Raw = `&nwarr;`  // ↖ north-west arrow
	UpRightArrow         mx.Raw = `&nearr;`  // ↗ north-east arrow
	DownLeftArrow        mx.Raw = `&swarr;`  // ↙ south-west arrow
	DownRightArrow       mx.Raw = `&searr;`  // ↘ south-east arrow
	DoubleLeftArrow      mx.Raw = `&lArr;`   // ⇐ leftwards double arrow
	DoubleRightArrow     mx.Raw = `&rArr;`   // ⇒ rightwards double arrow (implies)
	DoubleUpArrow        mx.Raw = `&uArr;`   // ⇑ upwards double arrow
	DoubleDownArrow      mx.Raw = `&dArr;`   // ⇓ downwards double arrow
	DoubleLeftRightArrow mx.Raw = `&hArr;`   // ⇔ left-right double arrow (iff)
	MapsTo               mx.Raw = `&mapsto;` // ↦ rightwards arrow from bar (maps to)
	HookLeftArrow        mx.Raw = `&larrhk;` // ↩ leftwards arrow with hook
	HookRightArrow       mx.Raw = `&rarrhk;` // ↪ rightwards arrow with hook
	CarriageReturn       mx.Raw = `&crarr;`  // ↵ downwards arrow with corner leftwards
	NotRightArrow        mx.Raw = `&nrarr;`  // ↛ rightwards arrow with stroke (not)
	LongLeftArrow        mx.Raw = `&xlarr;`  // ⟵ long leftwards arrow
	LongRightArrow       mx.Raw = `&xrarr;`  // ⟶ long rightwards arrow
	LongLeftRightArrow   mx.Raw = `&xharr;`  // ⟷ long left-right arrow
	LeftHarpoonUp        mx.Raw = `&lharu;`  // ↼ leftwards harpoon with barb up
	RightHarpoonUp       mx.Raw = `&rharu;`  // ⇀ rightwards harpoon with barb up
	LeftHarpoonDown      mx.Raw = `&lhard;`  // ↽ leftwards harpoon with barb down
	RightHarpoonDown     mx.Raw = `&rhard;`  // ⇁ rightwards harpoon with barb down
	Equilibrium          mx.Raw = `&rlhar;`  // ⇌ rightwards harpoon over leftwards harpoon
	ReverseEquilibrium   mx.Raw = `&lrhar;`  // ⇋ leftwards harpoon over rightwards harpoon

	// Geometric shapes.

	BlackStar          mx.Raw = `&starf;`   // ★ black star
	WhiteStar          mx.Raw = `&star;`    // ☆ white star
	Lozenge            mx.Raw = `&loz;`     // ◊ lozenge
	WhiteSquare        mx.Raw = `&square;`  // □ white square
	BlackSquare        mx.Raw = `&squf;`    // ▪ black small square
	WhiteCircle        mx.Raw = `&cir;`     // ○ white circle
	LargeCircle        mx.Raw = `&bigcirc;` // ◯ large circle
	UpTriangle         mx.Raw = `&utri;`    // ▵ white up-pointing triangle
	BlackUpTriangle    mx.Raw = `&utrif;`   // ▴ black up-pointing triangle
	DownTriangle       mx.Raw = `&dtri;`    // ▿ white down-pointing triangle
	BlackDownTriangle  mx.Raw = `&dtrif;`   // ▾ black down-pointing triangle
	RightTriangle      mx.Raw = `&rtri;`    // ▹ white right-pointing triangle
	BlackRightTriangle mx.Raw = `&rtrif;`   // ▸ black right-pointing triangle
	LeftTriangle       mx.Raw = `&ltri;`    // ◃ white left-pointing triangle
	BlackLeftTriangle  mx.Raw = `&ltrif;`   // ◂ black left-pointing triangle
	BlackLozenge       mx.Raw = `&lozf;`    // ⧫ black lozenge
	Rectangle          mx.Raw = `&rect;`    // ▭ white rectangle

	// Cards, music, and other symbols.

	Heart     mx.Raw = `&hearts;`    // ♥ heart suit
	Diamond   mx.Raw = `&diams;`     // ♦ diamond suit
	Club      mx.Raw = `&clubs;`     // ♣ club suit
	Spade     mx.Raw = `&spades;`    // ♠ spade suit
	CheckMark mx.Raw = `&checkmark;` // ✓ check mark
	BallotX   mx.Raw = `&cross;`     // ✗ ballot x (cross mark)
	MusicNote mx.Raw = `&sung;`      // ♪ eighth note
	Flat      mx.Raw = `&flat;`      // ♭ music flat sign
	Natural   mx.Raw = `&natur;`     // ♮ music natural sign
	Sharp     mx.Raw = `&sharp;`     // ♯ music sharp sign
	Male      mx.Raw = `&male;`      // ♂ male sign
	Female    mx.Raw = `&female;`    // ♀ female sign
	Telephone mx.Raw = `&phone;`     // ☎ telephone sign

	// Spacing diacritical marks.

	Acute       mx.Raw = `&acute;` // ´ acute accent
	Circumflex  mx.Raw = `&circ;`  // ˆ modifier circumflex accent
	Tilde       mx.Raw = `&tilde;` // ˜ small tilde
	Macron      mx.Raw = `&macr;`  // ¯ macron
	Diaeresis   mx.Raw = `&uml;`   // ¨ diaeresis (umlaut)
	Cedilla     mx.Raw = `&cedil;` // ¸ cedilla
	Breve       mx.Raw = `&breve;` // ˘ breve
	Caron       mx.Raw = `&caron;` // ˇ caron (háček)
	RingAbove   mx.Raw = `&ring;`  // ˚ ring above
	DoubleAcute mx.Raw = `&dblac;` // ˝ double acute accent
	Ogonek      mx.Raw = `&ogon;`  // ˛ ogonek
)
