package html

import "github.com/ungerik/go-mx"

type Text = mx.Text

func Textf(format string, args ...any) Text {
	return mx.Textf(format, args...)
}

func A(attribsChildren ...any) *Element            { return NewElement("a", attribsChildren...) }
func Abbr(attribsChildren ...any) *Element         { return NewElement("abbr", attribsChildren...) }
func Acronym(attribsChildren ...any) *Element      { return NewElement("acronym", attribsChildren...) }
func Address(attribsChildren ...any) *Element      { return NewElement("address", attribsChildren...) }
func Area(attribs ...Attrib) *Element              { return NewVoidElement("area", attribs...) }
func Article(attribsChildren ...any) *Element      { return NewElement("article", attribsChildren...) }
func Aside(attribsChildren ...any) *Element        { return NewElement("aside", attribsChildren...) }
func Audio(attribsChildren ...any) *Element        { return NewElement("audio", attribsChildren...) }
func B(attribsChildren ...any) *Element            { return NewElement("b", attribsChildren...) }
func Base(attribs ...Attrib) *Element              { return NewVoidElement("base", attribs...) }
func BDI(attribsChildren ...any) *Element          { return NewElement("bdi", attribsChildren...) }
func BDO(attribsChildren ...any) *Element          { return NewElement("bdo", attribsChildren...) }
func Big(attribsChildren ...any) *Element          { return NewElement("big", attribsChildren...) }
func Blockquote(attribsChildren ...any) *Element   { return NewElement("blockquote", attribsChildren...) }
func Body(attribsChildren ...any) *Element         { return NewElement("body", attribsChildren...) }
func Br(attribs ...Attrib) *Element                { return NewVoidElement("br", attribs...) }
func Button(attribsChildren ...any) *Element       { return NewElement("button", attribsChildren...) }
func Canvas(attribsChildren ...any) *Element       { return NewElement("canvas", attribsChildren...) }
func Caption(attribsChildren ...any) *Element      { return NewElement("caption", attribsChildren...) }
func Center(attribsChildren ...any) *Element       { return NewElement("center", attribsChildren...) }
func Cite(attribsChildren ...any) *Element         { return NewElement("cite", attribsChildren...) }
func Code(attribsChildren ...any) *Element         { return NewElement("code", attribsChildren...) }
func Col(attribs ...Attrib) *Element               { return NewVoidElement("col", attribs...) }
func ColGroup(attribsChildren ...any) *Element     { return NewElement("colgroup", attribsChildren...) }
func Content(attribsChildren ...any) *Element      { return NewElement("content", attribsChildren...) }
func Data(attribsChildren ...any) *Element         { return NewElement("data", attribsChildren...) }
func DataList(attribsChildren ...any) *Element     { return NewElement("datalist", attribsChildren...) }
func DD(attribsChildren ...any) *Element           { return NewElement("dd", attribsChildren...) }
func Del(attribsChildren ...any) *Element          { return NewElement("del", attribsChildren...) }
func Details(attribsChildren ...any) *Element      { return NewElement("details", attribsChildren...) }
func Dfn(attribsChildren ...any) *Element          { return NewElement("dfn", attribsChildren...) }
func Dialog(attribsChildren ...any) *Element       { return NewElement("dialog", attribsChildren...) }
func Div(attribsChildren ...any) *Element          { return NewElement("div", attribsChildren...) }
func DL(attribsChildren ...any) *Element           { return NewElement("dl", attribsChildren...) }
func DT(attribsChildren ...any) *Element           { return NewElement("dt", attribsChildren...) }
func Em(attribsChildren ...any) *Element           { return NewElement("em", attribsChildren...) }
func Embed(attribs ...Attrib) *Element             { return NewVoidElement("embed", attribs...) }
func FieldSet(attribsChildren ...any) *Element     { return NewElement("fieldset", attribsChildren...) }
func FigCaption(attribsChildren ...any) *Element   { return NewElement("figcaption", attribsChildren...) }
func Figure(attribsChildren ...any) *Element       { return NewElement("figure", attribsChildren...) }
func Font(attribsChildren ...any) *Element         { return NewElement("font", attribsChildren...) }
func Footer(attribsChildren ...any) *Element       { return NewElement("footer", attribsChildren...) }
func Form(attribsChildren ...any) *Element         { return NewElement("form", attribsChildren...) }
func Frame(attribsChildren ...any) *Element        { return NewElement("frame", attribsChildren...) }
func FrameSet(attribsChildren ...any) *Element     { return NewElement("frameset", attribsChildren...) }
func H1(attribsChildren ...any) *Element           { return NewElement("h1", attribsChildren...) }
func H2(attribsChildren ...any) *Element           { return NewElement("h2", attribsChildren...) }
func H3(attribsChildren ...any) *Element           { return NewElement("h3", attribsChildren...) }
func H4(attribsChildren ...any) *Element           { return NewElement("h4", attribsChildren...) }
func H5(attribsChildren ...any) *Element           { return NewElement("h5", attribsChildren...) }
func H6(attribsChildren ...any) *Element           { return NewElement("h6", attribsChildren...) }
func Head(attribsChildren ...any) *Element         { return NewElement("head", attribsChildren...) }
func Header(attribsChildren ...any) *Element       { return NewElement("header", attribsChildren...) }
func Hgroup(attribsChildren ...any) *Element       { return NewElement("hgroup", attribsChildren...) }
func HR(attribs ...Attrib) *Element                { return NewVoidElement("hr", attribs...) }
func HTML(attribsChildren ...any) *Element         { return NewElement("html", attribsChildren...) }
func I(attribsChildren ...any) *Element            { return NewElement("i", attribsChildren...) }
func IFrame(attribsChildren ...any) *Element       { return NewElement("iframe", attribsChildren...) }
func Image(attribsChildren ...any) *Element        { return NewElement("image", attribsChildren...) }
func Img(attribs ...Attrib) *Element               { return NewVoidElement("img", attribs...) }
func Input(attribs ...Attrib) *Element             { return NewVoidElement("input", attribs...) }
func Ins(attribsChildren ...any) *Element          { return NewElement("ins", attribsChildren...) }
func Kbd(attribsChildren ...any) *Element          { return NewElement("kbd", attribsChildren...) }
func Label(attribsChildren ...any) *Element        { return NewElement("label", attribsChildren...) }
func Legend(attribsChildren ...any) *Element       { return NewElement("legend", attribsChildren...) }
func LI(attribsChildren ...any) *Element           { return NewElement("li", attribsChildren...) }
func Link(attribs ...Attrib) *Element              { return NewVoidElement("link", attribs...) }
func Main(attribsChildren ...any) *Element         { return NewElement("main", attribsChildren...) }
func Map(attribsChildren ...any) *Element          { return NewElement("map", attribsChildren...) }
func Mark(attribsChildren ...any) *Element         { return NewElement("mark", attribsChildren...) }
func Marquee(attribsChildren ...any) *Element      { return NewElement("marquee", attribsChildren...) }
func Math(attribsChildren ...any) *Element         { return NewElement("math", attribsChildren...) }
func Menu(attribsChildren ...any) *Element         { return NewElement("menu", attribsChildren...) }
func MenuItem(attribsChildren ...any) *Element     { return NewElement("menuitem", attribsChildren...) }
func Meta(attribs ...Attrib) *Element              { return NewVoidElement("meta", attribs...) }
func Meter(attribsChildren ...any) *Element        { return NewElement("meter", attribsChildren...) }
func Nav(attribsChildren ...any) *Element          { return NewElement("nav", attribsChildren...) }
func NoBr(attribsChildren ...any) *Element         { return NewElement("nobr", attribsChildren...) }
func NoEmbed(attribsChildren ...any) *Element      { return NewElement("noembed", attribsChildren...) }
func NoFrames(attribsChildren ...any) *Element     { return NewElement("noframes", attribsChildren...) }
func NoScript(attribsChildren ...any) *Element     { return NewElement("noscript", attribsChildren...) }
func Object(attribsChildren ...any) *Element       { return NewElement("object", attribsChildren...) }
func OL(attribsChildren ...any) *Element           { return NewElement("ol", attribsChildren...) }
func OptGroup(attribsChildren ...any) *Element     { return NewElement("optgroup", attribsChildren...) }
func Option(attribsChildren ...any) *Element       { return NewElement("option", attribsChildren...) }
func Output(attribsChildren ...any) *Element       { return NewElement("output", attribsChildren...) }
func P(attribsChildren ...any) *Element            { return NewElement("p", attribsChildren...) }
func Picture(attribsChildren ...any) *Element      { return NewElement("picture", attribsChildren...) }
func Plaintext(attribsChildren ...any) *Element    { return NewElement("plaintext", attribsChildren...) }
func Portal(attribsChildren ...any) *Element       { return NewElement("portal", attribsChildren...) }
func Pre(attribsChildren ...any) *Element          { return NewElement("pre", attribsChildren...) }
func Progress(attribsChildren ...any) *Element     { return NewElement("progress", attribsChildren...) }
func Q(attribsChildren ...any) *Element            { return NewElement("q", attribsChildren...) }
func RB(attribsChildren ...any) *Element           { return NewElement("rb", attribsChildren...) }
func RP(attribsChildren ...any) *Element           { return NewElement("rp", attribsChildren...) }
func RT(attribsChildren ...any) *Element           { return NewElement("rt", attribsChildren...) }
func RTC(attribsChildren ...any) *Element          { return NewElement("rtc", attribsChildren...) }
func Ruby(attribsChildren ...any) *Element         { return NewElement("ruby", attribsChildren...) }
func S(attribsChildren ...any) *Element            { return NewElement("s", attribsChildren...) }
func Samp(attribsChildren ...any) *Element         { return NewElement("samp", attribsChildren...) }
func Script(attribsChildren ...any) *Element       { return NewElement("script", attribsChildren...) }
func Search(attribsChildren ...any) *Element       { return NewElement("search", attribsChildren...) }
func Section(attribsChildren ...any) *Element      { return NewElement("section", attribsChildren...) }
func Select(attribsChildren ...any) *Element       { return NewElement("select", attribsChildren...) }
func Shadow(attribsChildren ...any) *Element       { return NewElement("shadow", attribsChildren...) }
func Slot(attribsChildren ...any) *Element         { return NewElement("slot", attribsChildren...) }
func Small(attribsChildren ...any) *Element        { return NewElement("small", attribsChildren...) }
func Source(attribs ...Attrib) *Element            { return NewVoidElement("source", attribs...) }
func Span(attribsChildren ...any) *Element         { return NewElement("span", attribsChildren...) }
func Strike(attribsChildren ...any) *Element       { return NewElement("strike", attribsChildren...) }
func Strong(attribsChildren ...any) *Element       { return NewElement("strong", attribsChildren...) }
func StyleElem(attribsChildren ...any) *Element    { return NewElement("style", attribsChildren...) }
func Sub(attribsChildren ...any) *Element          { return NewElement("sub", attribsChildren...) }
func Summary(attribsChildren ...any) *Element      { return NewElement("summary", attribsChildren...) }
func Sup(attribsChildren ...any) *Element          { return NewElement("sup", attribsChildren...) }
func Svg(attribsChildren ...any) *Element          { return NewElement("svg", attribsChildren...) }
func Table(attribsChildren ...any) *Element        { return NewElement("table", attribsChildren...) }
func TBody(attribsChildren ...any) *Element        { return NewElement("tbody", attribsChildren...) }
func TD(attribsChildren ...any) *Element           { return NewElement("td", attribsChildren...) }
func TemplateElem(attribsChildren ...any) *Element { return NewElement("template", attribsChildren...) }
func TextArea(attribsChildren ...any) *Element     { return NewElement("textarea", attribsChildren...) }
func TFoot(attribsChildren ...any) *Element        { return NewElement("tfoot", attribsChildren...) }
func TH(attribsChildren ...any) *Element           { return NewElement("th", attribsChildren...) }
func THead(attribsChildren ...any) *Element        { return NewElement("thead", attribsChildren...) }
func Time(attribsChildren ...any) *Element         { return NewElement("time", attribsChildren...) }
func TitleElem(attribsChildren ...any) *Element    { return NewElement("title", attribsChildren...) }
func TR(attribsChildren ...any) *Element           { return NewElement("tr", attribsChildren...) }
func Track(attribsChildren ...any) *Element        { return NewElement("track", attribsChildren...) }
func TT(attribsChildren ...any) *Element           { return NewElement("tt", attribsChildren...) }
func U(attribsChildren ...any) *Element            { return NewElement("u", attribsChildren...) }
func UL(attribsChildren ...any) *Element           { return NewElement("ul", attribsChildren...) }
func Var(attribsChildren ...any) *Element          { return NewElement("var", attribsChildren...) }
func Video(attribsChildren ...any) *Element        { return NewElement("video", attribsChildren...) }
func WBr(attribs ...Attrib) *Element               { return NewVoidElement("wbr", attribs...) }
